# Generated by Django 3.1.2 on 2020-11-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(blank=True, choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Approved', 'Approved')], max_length=200, null=True),
        ),
    ]
