# Generated by Django 3.1.2 on 2020-10-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='useraname',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('CH', 'Cashier'), ('DR', 'Doctor'), ('PHM', 'Pharmacy'), ('HM', 'Hospital Manager'), ('IT', 'IT'), ('ACC', 'Accountant'), ('HR', 'Human Resource'), ('NRS', 'Nurse')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('MU', 'Manager'), ('NU', 'Normal Support'), ('SU', 'Support'), ('AD', 'Administration')], max_length=255, null=True),
        ),
    ]
