# Generated by Django 3.1.2 on 2020-11-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201012_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Dismissed', 'Dismissed'), ('Leave', 'Leave'), ('Suspended', 'Suspended')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ACC', 'Accountant'), ('NRS', 'Nurse'), ('DR', 'Doctor'), ('HM', 'Hospital Manager'), ('HR', 'Human Resource'), ('IT', 'IT'), ('CH', 'Cashier'), ('PHM', 'Pharmacy')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('NU', 'Normal Support'), ('MU', 'Manager'), ('AD', 'Administrator'), ('SU', 'Support')], max_length=255, null=True),
        ),
    ]
