# Generated by Django 3.1.2 on 2020-11-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201110_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('HM', 'Hospital Manager'), ('CH', 'Cashier'), ('DR', 'Doctor'), ('PHM', 'Pharmacy'), ('HR', 'Human Resource'), ('NRS', 'Nurse'), ('ACC', 'Accountant'), ('IT', 'IT')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('Dismissed', 'Dismissed'), ('Leave', 'Leave'), ('Suspended', 'Suspended'), ('Active', 'Active')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('SU', 'Support'), ('MU', 'Manager'), ('AD', 'Administrator'), ('NU', 'Normal Support')], max_length=255, null=True),
        ),
    ]
