# Generated by Django 3.1.2 on 2020-11-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201110_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resource'), ('HM', 'Hospital Manager'), ('CH', 'Cashier'), ('DR', 'Doctor'), ('IT', 'IT'), ('NRS', 'Nurse'), ('PHM', 'Pharmacy'), ('ACC', 'Accountant')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('Suspended', 'Suspended'), ('Active', 'Active'), ('Dismissed', 'Dismissed'), ('Leave', 'Leave')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('SU', 'Support'), ('NU', 'Normal Support'), ('MU', 'Manager'), ('AD', 'Administrator')], max_length=255, null=True),
        ),
    ]
