# Generated by Django 3.1.2 on 2020-11-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201110_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resource'), ('ACC', 'Accountant'), ('IT', 'IT'), ('DR', 'Doctor'), ('CH', 'Cashier'), ('NRS', 'Nurse'), ('HM', 'Hospital Manager'), ('PHM', 'Pharmacy')], max_length=255, null=True),
        ),
    ]
