# Generated by Django 3.1.2 on 2020-11-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201110_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('PHM', 'Pharmacy'), ('NRS', 'Nurse'), ('DR', 'Doctor'), ('HR', 'Human Resource'), ('IT', 'IT'), ('ACC', 'Accountant'), ('HM', 'Hospital Manager'), ('CH', 'Cashier')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Dismissed', 'Dismissed'), ('Suspended', 'Suspended'), ('Leave', 'Leave')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('AD', 'Administrator'), ('MU', 'Manager'), ('SU', 'Support'), ('NU', 'Normal Support')], max_length=255, null=True),
        ),
    ]
