# Generated by Django 3.1.2 on 2020-11-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20201103_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='number',
        ),
        migrations.AddField(
            model_name='bill',
            name='number_of_days',
            field=models.IntegerField(blank=True, choices=[(1, 'Paid'), (0, 'Not Paid')], null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('LB', 'Lab Bills'), ('WB', 'Ward Bills'), ('CB', 'Card Bills'), ('PhB', 'Pharmacy Bills')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Paid'), (0, 'Not Paid')], null=True),
        ),
        migrations.AlterField(
            model_name='defaultbill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('LB', 'Lab Bills'), ('WB', 'Ward Bills'), ('CB', 'Card Bills'), ('PhB', 'Pharmacy Bills')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defaultbill',
            name='number_of_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
