# Generated by Django 3.1.2 on 2020-11-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20201110_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('PB', 'Procedure Bills'), ('CB', 'Card Bills'), ('CnB', 'Consultation Bills'), ('LB', 'Lab Bills'), ('PhB', 'Pharmacy Bills'), ('WB', 'Ward Bills')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='number_of_days',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Paid'), (1, 'Paid')], null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Paid'), (1, 'Paid')], null=True),
        ),
        migrations.AlterField(
            model_name='defaultbill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('PB', 'Procedure Bills'), ('CB', 'Card Bills'), ('CnB', 'Consultation Bills'), ('LB', 'Lab Bills'), ('PhB', 'Pharmacy Bills'), ('WB', 'Ward Bills')], max_length=100, null=True),
        ),
    ]
