# Generated by Django 3.1.2 on 2020-11-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20201112_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('PhB', 'Pharmacy Bills'), ('CnB', 'Consultation Bills'), ('LB', 'Lab Bills'), ('WB', 'Ward Bills'), ('CB', 'Card Bills'), ('PB', 'Procedure Bills')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defaultbill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('PhB', 'Pharmacy Bills'), ('CnB', 'Consultation Bills'), ('LB', 'Lab Bills'), ('WB', 'Ward Bills'), ('CB', 'Card Bills'), ('PB', 'Procedure Bills')], max_length=100, null=True),
        ),
    ]
