# Generated by Django 3.1.2 on 2020-11-12 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_auto_20201112_1456'),
        ('portal', '0008_auto_20201112_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_prescription', to='pharmacy.prescription'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('PB', 'Procedure Bills'), ('CB', 'Card Bills'), ('CnB', 'Consultation Bills'), ('WB', 'Ward Bills'), ('PhB', 'Pharmacy Bills'), ('LB', 'Lab Bills')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='number_of_days',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Paid'), (1, 'Paid')], null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Paid'), (1, 'Paid')], null=True),
        ),
        migrations.AlterField(
            model_name='defaultbill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('PB', 'Procedure Bills'), ('CB', 'Card Bills'), ('CnB', 'Consultation Bills'), ('WB', 'Ward Bills'), ('PhB', 'Pharmacy Bills'), ('LB', 'Lab Bills')], max_length=100, null=True),
        ),
    ]
