# Generated by Django 3.1.2 on 2020-11-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-created_at',)},
        ),
    ]
