# Generated by Django 3.1.2 on 2020-10-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20201020_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedallocate',
            name='discharged_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], max_length=100, null=True),
        ),
    ]
