# Generated by Django 3.1.2 on 2020-10-20 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20201020_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='allocate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_allocate', to='management.bedallocate'),
        ),
        migrations.AddField(
            model_name='bed',
            name='bed_allocates',
            field=models.ManyToManyField(blank=True, related_name='bed_bed_allocates', to='management.BedAllocate'),
        ),
        migrations.AddField(
            model_name='bed',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
