# Generated by Django 3.1.2 on 2020-10-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('management', '0008_auto_20201022_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='patient_notes', to='department.Note'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], max_length=100, null=True),
        ),
    ]
