# Generated by Django 3.1.2 on 2020-10-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20201022_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaldiagnosis',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='admitted_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='discharge_at',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_admitted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_discharged',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='time_admitted',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='time_discharged',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Single', 'Single')], max_length=100, null=True),
        ),
    ]
