# Generated by Django 3.1.2 on 2020-10-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20201027_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bedallocate',
            old_name='admitted_at',
            new_name='date_admitted',
        ),
        migrations.RenameField(
            model_name='bedallocate',
            old_name='discharged_at',
            new_name='date_discharged',
        ),
        migrations.AddField(
            model_name='bedallocate',
            name='time_admitted',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bedallocate',
            name='time_discharged',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(blank=True, choices=[('Unassigned', 'Unassigned'), ('Assigned', 'Assigned')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Widowed', 'Widowed'), ('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(blank=True, choices=[('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
    ]
