# Generated by Django 3.1.2 on 2020-11-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20201105_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='seen',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(blank=True, choices=[('Assigned', 'Assigned'), ('Unassigned', 'Unassigned')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(blank=True, choices=[('Resolved', 'Resolved'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], max_length=100, null=True),
        ),
    ]
