# Generated by Django 3.1.2 on 2020-11-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_auto_20201109_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Resolved', 'Resolved')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Divorced', 'Divorced'), ('Married', 'Married'), ('Widowed', 'Widowed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='department',
            field=models.CharField(blank=True, choices=[('Account', 'Account'), ('Management', 'Management'), ('HR', 'Human Resource'), ('Ward', 'Ward'), ('Pharmacy', 'Pharmacy')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
    ]
