# Generated by Django 3.1.2 on 2020-11-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_auto_20201110_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='pharmacy_treatment',
            new_name='pharmacy_prescription',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(blank=True, choices=[('Resolved', 'Resolved'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Widowed', 'Widowed'), ('Single', 'Single'), ('Divorced', 'Divorced')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resource'), ('Management', 'Management'), ('Account', 'Account'), ('Pharmacy', 'Pharmacy'), ('Ward', 'Ward')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Accepted'), (2, 'Rejected'), (0, 'Pending')], null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(blank=True, choices=[('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
    ]
