# Generated by Django 3.1.2 on 2020-11-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_auto_20201112_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveperiod',
            old_name='days_allocated',
            new_name='days_allowed',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(blank=True, choices=[('Resolved', 'Resolved'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Divorced', 'Divorced'), ('Single', 'Single'), ('Widowed', 'Widowed'), ('Married', 'Married')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='department',
            field=models.CharField(blank=True, choices=[('Pharmacy', 'Pharmacy'), ('Management', 'Management'), ('Account', 'Account'), ('Ward', 'Ward'), ('HR', 'Human Resource')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(blank=True, choices=[(2, 'Rejected'), (0, 'Pending'), (1, 'Accepted')], null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], max_length=100, null=True),
        ),
    ]
