# Generated by Django 3.1.2 on 2020-11-10 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0002_auto_20201109_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='pieces_selling_price',
            new_name='cost_price_per_box',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='boxes_sold',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='pieces',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='pieces_left',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='pieces_per_box',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='pieces_sold',
        ),
        migrations.AddField(
            model_name='medicine',
            name='cost_price_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='no_in_box',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='selling_price_per_box',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='selling_price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='sold_boxes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='sold_units',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='total_no_units_accumulated',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='total_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='units_left',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='boxes_bought',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='boxes_left',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='prescribed_medicines',
            field=models.ManyToManyField(blank=True, related_name='medicine_prescribed_medicines', to='pharmacy.PrescribedMedicine'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Unpaid'), (1, 'Paid')], null=True),
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditures', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditure_medicine', to='pharmacy.medicine')),
            ],
            options={
                'db_table': 'expenditure',
            },
        ),
    ]
