# Generated by Django 3.1.2 on 2020-11-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_auto_20201110_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='accumulated_boxes_bought',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='accumulated_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('Tablet', 'Tablet'), ('Syrup', 'Syrup'), ('Capsule', 'Capsule')], max_length=100, null=True),
        ),
    ]
