# Generated by Django 3.1.2 on 2020-11-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_auto_20201110_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='cost_price_unit',
            new_name='cost_price_per_unit',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('Syrup', 'Syrup'), ('Capsule', 'Capsule'), ('Tablet', 'Tablet')], max_length=100, null=True),
        ),
    ]
