# Generated by Django 3.1.2 on 2020-11-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_auto_20201110_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='item',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
