# Generated by Django 3.1.2 on 2020-11-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_auto_20201111_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Tablet', 'Tablet')], max_length=100, null=True),
        ),
    ]
