# Generated by Django 3.1.2 on 2020-11-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_auto_20201112_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup')], max_length=100, null=True),
        ),
    ]
