# Generated by Django 3.1.2 on 2020-11-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_auto_20201112_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, choices=[('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Tablet', 'Tablet')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Confirmed')], null=True),
        ),
    ]
